In [1]:
import sys
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt

In [2]:
filename = 'balls.png'
src = cv.imread(cv.samples.findFile(filename), cv.IMREAD_COLOR)
if src is None:
    print ('Error opening image!')
    print ('Usage: hough_circle.py [image_name -- default ' + default_file + '] \n')

In [3]:
def get_color(img, x, y, r):
    height, width = img.shape[:2]
    roi_size = 20
    roi_values = img[(y-roi_size):(y+roi_size),(x-roi_size):(x+roi_size)]
    mean_blue = np.mean(roi_values[:,:,0])
    mean_green = np.mean(roi_values[:,:,1])
    mean_red = np.mean(roi_values[:,:,2])
    rgb = {"red":mean_red, "green":mean_green, "blue":mean_blue}
    return max(rgb, key=rgb.get)

In [5]:
# convert the image to greyscale
gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)

# apply blur for noise reduction
gray = cv.medianBlur(gray, 5)
print(gray.shape)
rows = gray.shape[0]

# apply Hough gradient
circles = cv.HoughCircles(gray, cv.HOUGH_GRADIENT, 1, rows / 8, param1=100, param2=30, minRadius=1, maxRadius=300)
balls = []
print(circles)

if circles is not None:
    circles = np.uint16(np.around(circles))
    for i in circles[0, :]:
        x = i[0]
        y = i[1]
        r = i[2]
        balls.append([x,y,r,get_color(src, x, y, r)])
print(balls)
# display_image(hsv, 'hsv')
# cv.imshow("detected caircles", src)
# cv.imshow("hsv", hsv)
# cv.waitKey(0)

(638, 999)
[[[499.5 141.5  60.1]
  [743.5 402.5  59.5]
  [209.5 215.5  59.7]
  [329.5 494.5  59.7]
  [817.5 197.5  57.6]]]
[[500, 142, 60, 'blue'], [744, 402, 60, 'red'], [210, 216, 60, 'blue'], [330, 494, 60, 'red'], [818, 198, 58, 'green']]
